DELETE FROM `product_images` WHERE `product_id` IN (SELECT `id` FROM `products` WHERE `sku` IN ('ACC-CAB-001','AUD-AUD-002','ACC-VEH-003','ACC-POR-004','ACC-SOP-005','ACC-ADA-006','ACC-EST-007'));
DELETE FROM `products` WHERE `sku` IN ('ACC-CAB-001','AUD-AUD-002','ACC-VEH-003','ACC-POR-004','ACC-SOP-005','ACC-ADA-006','ACC-EST-007');

INSERT INTO `products` (
  `id`, `category_id`, `brand_id`, `name`, `slug`, `sku`, `short_description`, `description`,
  `specifications`, `features`, `warranty`, `price`, `original_price`, `discount_percent`,
  `cost_price`, `stock`, `min_stock`, `weight`, `dimensions`, `is_active`, `is_featured`,
  `is_new`, `is_on_sale`, `sale_starts_at`, `sale_ends_at`, `meta_title`, `meta_description`
) VALUES
(100, 6, 1, 'Cables y Cargadores para Celulares', 'cables-cargadores-celulares', 'ACC-CAB-001', 'Kit completo de cables y cargadores universales para celulares', '<p>Kit completo de cables y cargadores universales para celulares. Compatible con USB-C, Lightning y Micro USB.</p>', JSON_OBJECT('Conectores', 'USB-C, Lightning, Micro USB', 'Longitud', '1m / 2m', 'Material', 'Nylon trenzado'), JSON_ARRAY('Universal', 'Carga rápida', 'Durable', 'Multiple conectores'), '12 meses', 15900, 24900, 36, 9500, 50, 3, 0.05, '20 x 10 x 5 cm', TRUE, TRUE, FALSE, TRUE, DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), 'Cables y Cargadores para Celulares', 'Kit completo de cables y cargadores universales.'),
(101, 1, 1, 'Audífonos', 'audifonos', 'AUD-AUD-002', 'Audífonos over-ear con sonido envolvente y micrófono integrado', '<p>Audífonos over-ear con sonido envolvente y micrófono integrado. Ideales para gaming y llamadas.</p>', JSON_OBJECT('Driver', '40mm', 'Bluetooth', '5.2', 'Autonomía', '20 horas', 'Peso', '260g'), JSON_ARRAY('Sonido envolvente', 'Micrófono', 'Comodidad', 'Plegables'), '12 meses', 29900, 45900, 35, 18000, 35, 3, 0.28, '18 x 16 x 8 cm', TRUE, TRUE, TRUE, TRUE, DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), 'Audífonos', 'Audífonos over-ear con sonido premium.'),
(102, 7, 10, 'Cargadores Vehiculares', 'cargadores-vehiculares', 'ACC-VEH-003', 'Cargador dual para auto con puerto USB-C y USB-A', '<p>Cargador dual para auto con puerto USB-C y USB-A. Carga rápida para tus dispositivos en viaje.</p>', JSON_OBJECT('Puertos', 'USB-C + USB-A', 'Potencia', '36W', 'Entrada', '12-24V DC'), JSON_ARRAY('Dual USB', 'Carga rápida', 'Compacto', 'Protección integral'), '12 meses', 8900, 12900, 31, 5500, 60, 3, 0.06, '8 x 4 x 3 cm', TRUE, TRUE, FALSE, TRUE, DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), 'Cargadores Vehiculares', 'Cargador dual para auto USB-C y USB-A.'),
(103, 7, 10, 'Cargadores Portátiles', 'cargadores-portatiles', 'ACC-POR-004', 'Power bank de 20000mAh con carga rápida y doble puerto USB', '<p>Power bank de 20000mAh con carga rápida y doble puerto USB. Perfecto para el día a día.</p>', JSON_OBJECT('Capacidad', '20000mAh', 'Puertos', 'USB-C y USB-A', 'Potencia', '22.5W'), JSON_ARRAY('Carga rápida', 'Alta capacidad', 'Doble salida', 'Protección integral'), '12 meses', 12900, 19900, 35, 8000, 40, 5, 0.35, '15 x 7 x 3 cm', TRUE, TRUE, FALSE, TRUE, DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), 'Cargadores Portátiles', 'Power bank 20000mAh con carga rápida.'),
(104, 6, 10, 'Soportes Para Celulares', 'soportes-celulares', 'ACC-SOP-005', 'Soporte universal para celulares con ajuste 360°', '<p>Soporte universal para celulares con ajuste 360°. Compatible con todos los tamaños.</p>', JSON_OBJECT('Compatibilidad', 'Universal', 'Ajuste', '360° rotación', 'Material', 'Aluminio + silicona'), JSON_ARRAY('360°', 'Universal', 'Anti-deslizante', 'Ajustable'), '12 meses', 6900, 9900, 30, 4200, 70, 3, 0.08, '10 x 8 x 10 cm', TRUE, TRUE, FALSE, TRUE, DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), 'Soportes Para Celulares', 'Soporte universal 360° para celulares.'),
(105, 6, 10, 'Adaptadores', 'adaptadores', 'ACC-ADA-006', 'Pack de adaptadores universales: HDMI, VGA, USB-C y Ethernet', '<p>Pack de adaptadores universales: HDMI, VGA, USB-C y Ethernet. Conectividad total.</p>', JSON_OBJECT('Tipos', 'HDMI, VGA, USB-C, Ethernet', 'HDMI', '4K@30Hz', 'Ethernet', 'Gigabit'), JSON_ARRAY('Multifuncional', '4K HDMI', 'Gigabit LAN', 'Compacto'), '12 meses', 4900, 7900, 38, 3000, 80, 3, 0.12, '12 x 8 x 3 cm', TRUE, TRUE, TRUE, TRUE, DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), 'Adaptadores', 'Pack de adaptadores universales.'),
(106, 6, 1, 'Estuches Para Audífonos', 'estuches-audifonos', 'ACC-EST-007', 'Estuche protector para audífonos con interior acolchado', '<p>Estuche protector para audífonos con interior acolchado. Transporte seguro.</p>', JSON_OBJECT('Interior', 'Acolchado', 'Cierre', 'Cremallera', 'Material', 'Poliéster'), JSON_ARRAY('Protección', 'Portátil', 'Acolchado', 'Cierre seguro'), '12 meses', 3900, 5900, 34, 2400, 100, 3, 0.05, '20 x 10 x 8 cm', TRUE, TRUE, FALSE, TRUE, DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), 'Estuches Para Audífonos', 'Estuche protector para audífonos.'),
;

INSERT INTO `product_images` (`product_id`, `url`, `alt_text`, `is_main`, `sort_order`) VALUES
(100, '/images/producto1.webp', 'Cables y Cargadores para Celulares', TRUE, 0),
(101, '/images/producto1.webp', 'Audífonos', TRUE, 0),
(102, '/images/producto1.webp', 'Cargadores Vehiculares', TRUE, 0),
(103, '/images/producto1.webp', 'Cargadores Portátiles', TRUE, 0),
(104, '/images/producto1.webp', 'Soportes Para Celulares', TRUE, 0),
(105, '/images/producto1.webp', 'Adaptadores', TRUE, 0),
(106, '/images/producto1.webp', 'Estuches Para Audífonos', TRUE, 0);
